function execute() {
    return Response.success([
		{title: "Huyền Huuyễn", input: "https://truyenmoiz.com/the-loai/huyen-huyen", script: "gen.js"},
		{title: "Xuyên Không", input: "https://truyenmoiz.com/the-loai/xuyen-khong", script: "gen.js"},
		{title: "Truyện Teen", input: "https://truyenmoiz.com/the-loai/truyen-teen", script: "gen.js"},
		{title: "Tiên Hiệp", input: "https://truyenmoiz.com/the-loai/tien-hiep", script: "gen.js"},
		{title: "Ngôn Tình", input: "https://truyenmoiz.com/the-loai/ngon-tinh", script: "gen.js"},
		{title: "Tiểu Thuyết", input: "https://truyenmoiz.com/the-loai/tieu-thuyet", script: "gen.js"},
		{title: "Trinh Thám", input: "https://truyenmoiz.com/the-loai/trinh-tham", script: "gen.js"},
		{title: "Kiếm Hiệp", input: "https://truyenmoiz.com/the-loai/kiem-hiep", script: "gen.js"},
		{title: "Hệ Thống", input: "https://truyenmoiz.com/the-loai/he-thong", script: "gen.js"},
		{title: "Xuyên Nhanh", input: "https://truyenmoiz.com/the-loai/xuyen-nhanh", script: "gen.js"},
		{title: "Nữ Phụ", input: "https://truyenmoiz.com/the-loai/nu-phu", script: "gen.js"},
		{title: "Hài Hước", input: "https://truyenmoiz.com/the-loai/hai-huoc", script: "gen.js"},
		{title: "Nữ Cường", input: "https://truyenmoiz.com/the-loai/nu-cuong", script: "gen.js"},
		{title: "Lịch Sử", input: "https://truyenmoiz.com/the-loai/lich-su", script: "gen.js"},
		{title: "Light Novel", input: "https://truyenmoiz.com/the-loai/light-novel", script: "gen.js"},
		{title: "Dị Năng", input: "https://truyenmoiz.com/the-loai/di-nang", script: "gen.js"},
		{title: "Khoa Huyễn", input: "https://truyenmoiz.com/the-loai/khoa-huyen", script: "gen.js"},
		{title: "Sủng", input: "https://truyenmoiz.com/the-loai/sung", script: "gen.js"},
		{title: "Mạt Thế", input: "https://truyenmoiz.com/the-loai/mat-the", script: "gen.js"},
		{title: "Đam Mỹ", input: "https://truyenmoiz.com/the-loai/dam-my", script: "gen.js"},
		{title: "Đo Thị", input: "https://truyenmoiz.com/the-loai/do-thi", script: "gen.js"},
		{title: "Sắc", input: "https://truyenmoiz.com/the-loai/sac", script: "gen.js"},
		{title: "Cổ Đại", input: "https://truyenmoiz.com/the-loai/co-dai", script: "gen.js"},
		{title: "Dị Giới", input: "https://truyenmoiz.com/the-loai/di-gioi", script: "gen.js"},
        {title: "FanFic", input: "https://truyenmoiz.com/the-loai/fanfic", script: "gen.js"},
		{title: "Đồng Nhân", input: "https://truyenmoiz.com/the-loai/dong-nhan", script: "gen.js"},
		{title: "Truyện Audio", input: "https://truyenmoiz.com/the-loai/truyen-audio", script: "gen.js"},
		{title: "Thám Hiểm", input: "https://truyenmoiz.com/the-loai/tham-hiem", script: "gen.js"},
		{title: "Quan Trường", input: "https://truyenmoiz.com/the-loai/quan-truong", script: "gen.js"},
		{title: "Bách Hợp", input: "https://truyenmoiz.com/the-loai/bach-hop", script: "gen.js"},
		{title: "Quân Sự", input: "https://truyenmoiz.com/the-loai/quan-su", script: "gen.js"},
		{title: "Phương Tây", input: "https://truyenmoiz.com/the-loai/phuong-tay", script: "gen.js"},
		{title: "Việt Nam", input: "https://truyenmoiz.com/the-loai/viet-nam", script: "gen.js"},
		{title: "Đoản Văn", input: "https://truyenmoiz.com/the-loai/doan-van", script: "gen.js"},
		{title: "Cung Đấu", input: "https://truyenmoiz.com/the-loai/cung-dau", script: "gen.js"},
		{title: "Đông Phương", input: "https://truyenmoiz.com/the-loai/dong-phuong", script: "gen.js"},
		{title: "Linh Dị", input: "https://truyenmoiz.com/the-loai/linh-di", script: "gen.js"},
		{title: "Đièn Văn", input: "https://truyenmoiz.com/the-loai/dien-van", script: "gen.js"},
		{title: "Gia Đấu", input: "https://truyenmoiz.com/the-loai/gia-dau", script: "gen.js"},
		{title: "Trọng Sinh", input: "https://truyenmoiz.com/the-loai/trong-sinh", script: "gen.js"},
		{title: "Ngược", input: "https://truyenmoiz.com/the-loai/nguoc", script: "gen.js"},
		{title: "Khác", input: "https://truyenmoiz.com/the-loai/khac", script: "gen.js"},
		{title: "Võng Du", input: "https://truyenmoiz.com/the-loai/vong-du", script: "gen.js"}
		
		

}